"""add cascade delete for user foreign keys

Revision ID: 20836f8dcaaa
Revises: 2953ccd1500d
Create Date: 2026-07-01 23:26:50.306702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20836f8dcaaa'
down_revision: Union[str, Sequence[str], None] = '2953ccd1500d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('meal_plans_user_id_fkey'), 'meal_plans', type_='foreignkey')
    op.create_foreign_key(None, 'meal_plans', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'meal_plans', type_='foreignkey')
    op.create_foreign_key(op.f('meal_plans_user_id_fkey'), 'meal_plans', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
