"""add user daily request limits

Revision ID: 2b9c18d8b02e
Revises: 6d7d7044dcd2
Create Date: 2026-06-29 22:14:53.911276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9c18d8b02e'
down_revision: Union[str, Sequence[str], None] = '6d7d7044dcd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_requests', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_request_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'last_request_date')
    op.drop_column('users', 'daily_requests')
    # ### end Alembic commands ###
