"""add gender field to meal_plans table

Revision ID: 2953ccd1500d
Revises: 2b9c18d8b02e
Create Date: 2026-07-01 23:22:14.805990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2953ccd1500d'
down_revision: Union[str, Sequence[str], None] = '2b9c18d8b02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plans', sa.Column('gender', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plans', 'gender')
    # ### end Alembic commands ###
